name: Build VF2 Kernel

permissions:
  contents: write
  
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: tuxmake/riscv_gcc:latest
      options: --user root
      
    steps:
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::Build_$(date +"%Y.%m.%d_%H-%M")"
        
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master
      
    - name: Install dependencies
      run: apt install -y build-essential debhelper #gcc-riscv64-linux-gnu
      
    - name: Make visionfive2_defconfig
      run: make CROSS_COMPILE=riscv64-linux-gnu- ARCH=riscv visionfive2_defconfig

    - name: Make kernel
      run: make CROSS_COMPILE=riscv64-linux-gnu- ARCH=riscv -j`nproc`

    - name: Build .deb packages
      run: make CROSS_COMPILE=riscv64-linux-gnu- ARCH=riscv bindeb-pkg
      
    - name: Copy .deb to /tmp
      run: cp ../*.deb /tmp/
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: compiled_vf2_debs
        path: /tmp/*.deb
        retention-days: 5

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body: Automated build of VisionFive 2 kernel .debs for Ubuntu.
        files: |
          /tmp/*.deb
