name: Publish APT repo

permissions:
  contents: write
  
on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --user root

    steps:
    - name: Install dependencies
      run: |
        apt update
        apt install -y curl jq unzip
        
    - name: Find Artifact
      id: find_artifact
      run: |
        echo '::set-output name=artifact_id::$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/agreenbhm/linux/actions/artifacts | jq .artifacts[0].id)'
      
    - name: Download Artifact
      run: |
        curl -L -o /tmp/artifact.zip -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/agreenbhm/linux/actions/artifacts/${{ steps.find_artifact.outputs.artifact_id }}/zip
    
    - name: Extract Artifact
      run: |
        cd /tmp/
        unzip artifact.zip
        
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(basename /tmp/linux-image-* | cut -d'_' -f2)-$(date +'%Y.%m.%d_%H-%M')"

    - name: Display structure of downloaded files
      run: |
        cd /tmp/
        ls -R
    
    - name: Publish Repo
      uses: jrandiny/apt-repo-action@v1
      with:
        page_branch: apt
        github_token: ${{ secrets.PAT }}
        arch: |
          riscv
        version: |
          lunar
        file: /tmp/*.deb
        file_target_version: lunar
        public_key: ${{ secrets.PUBLIC }}
        private_key: ${{ secrets.PRIVATE }}
        key_passphrase: ${{ secrets.SECRET }}
