name: Release VF2 Kernel

permissions:
  contents: write
  
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      options: --user root

    steps:
    - name: Install dependencies
      run: apt install -y curl jq unzip
      
    - name: Download Artifacts
      run: cd /tmp && artifact_id=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/agreenbhm/linux/actions/artifacts | jq .artifacts[0].id) && export artifact_id

    - name: Print Artifact ID
      run: echo $artifact_id
    
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(basename /tmp/linux-image-* | cut -d'_' -f2)"

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: /tmp/

