name: Test

permissions:
  contents: write
  
on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-cache:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    container:
      image: ubuntu:latest
      options: --user root

    steps:    
    - name: Save Cache
    uses: actions/cache/save@v3
    with:
      path: |
        path/to/dependencies
        some/other/dependencies
      key: testcache1
      
    - name: Restore Cached Debs
      id: cache-debs-restore
      uses: actions/cache@v3
      with:
        path: |
          /tmp/
        key: testcache1
        
    - name: List /tmp/
      run: ls -laR /tmp/
