name: Update Repo

permissions:
  contents: write
  
on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --user root

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: apt
        fetch-depth: 1 
        
    - name: Install dependencies
      run: |
        apt update
        apt install -y apt-utils git curl jq unzip
      
    - name: Find Artifact
      id: find_artifact
      run: |
        echo '::set-output name=artifact_id::$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/agreenbhm/linux/actions/artifacts?name=compiled_vf2_debs | jq .artifacts[0].id)'
      
    - name: Download Artifact
      run: |
        curl -L -o /tmp/artifact.zip -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/agreenbhm/linux/actions/artifacts/${{ steps.find_artifact.outputs.artifact_id }}/zip
    
    - name: Extract Artifact
      run: |
        cd /tmp/
        unzip artifact.zip
    
    - name: Replace repo .deb files
      run: |
        rm -f ./repo/pool/main/*.deb
        mv /tmp/*.deb ./repo/pool/main/
        
    - name: Create Packages and Release manifests
      run: | 
        cd ./repo
        apt-ftparchive packages pool/ | gzip -9 > dists/dev/main/binary-riscv64/Packages.gz
        cd ./dists/dev
        apt-ftparchive release . | grep -v ".*Release$" > Release
        
    - name: Git Add/Commit/Push repo to GH
      run: |
        cd ../../
        echo `pwd`
        git config --global user.email "merge-upstream-action@github.com"
        git config --global user.name "Merge Upstream Action"
        git add .
        git commit -m "Updating apt repo" --no-edit
        git push origin apt
    

